### ISSUE TITLE
0.2.1 (current latest) nuget package of Sandbox LocalDB throws exception

### ISSUE THREAD

**Issue by karlomedallo** [ritterim/sandbox#19]
Tried running the latest available in nuget, but it throws exception. However, if I clone the latest from repo, it works fine.
I also noticed that the last few PRs were to update to 0.2.2 but it seems that it is not the version shown in nuget

**Comment by kendaleiv** [comment]
Version **0.2.2** has been published to NuGet. Thanks for letting us know!
